/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import static Logica.Main.miUefa;
import Logica.Partido;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pedro ortiz
 */
public class MostrarResultado extends javax.swing.JDialog {

    /**
     * Creates new form MostrarResultado
     * @param parent
     * @param modal
     * @param partido
     */
    
     DefaultTableModel md;
      DefaultTableModel md2;
    String datos[][]={};
    String columnas[]={"",""}; 
    

    public MostrarResultado(java.awt.Frame parent, boolean modal,Partido partido) {
        super(parent, modal);
        initComponents();
        
//        JLfecha2.setText(partido.getFecha().getTime().toString());
        JLlugar.setText(partido.getLocal().getEstadio());
        //JLarbitro.setText(partido.getArbitros().get(0).getNombre());
       
//
//        
//        md2 = new DefaultTableModel(datos,columnas);
//        md = new DefaultTableModel(datos,columnas);
//        jTable1.setModel(md);
//        jTable2.setModel(md2);
//        
//        Object v[] = new Object[2];
//        
//        for(int i=0;i<partido.getActa().getSucesos().size();i++){
//        v[0] = partido.getActa().getSucesos().get(i).getMinuto();
//        v[1] = partido.getActa().getSucesos().get(i).getImplicado().getNombre();
//        
//        if(partido.getActa().getSucesos().get(i).getImplicado().getEquipo()==partido.getLocal()){
//                
//        md.addRow(v);
//        }
//        else{md2.addRow(v);}
//        
//}
//        
        
          if(partido.getLocal().getEscudo()!=null){
               
            ImageIcon icon = new ImageIcon(partido.getLocal().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());          
             JLescudoLocal2.setText(null);
             JLescudoLocal2.setIcon(icono);
         }
             else{
                   
            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());          
            JLescudoLocal2.setText(null);
            JLescudoLocal2.setIcon(icono);
                 
           
                  }
          if(partido.getVisitante().getEscudo()!=null){
               
            ImageIcon icon = new ImageIcon(partido.getVisitante().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());          
             JLescudoVist2.setText(null);
             JLescudoVist2.setIcon(icono);
         }
             else{
                   
            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());          
            JLescudoVist2.setText(null);
            JLescudoVist2.setIcon(icono);
                 
           
                  }
          
          JTLocal.setText(partido.getLocal().getNombre());
          JTVist.setText(partido.getVisitante().getNombre());
          JLgolesLocal.setText(String.valueOf(partido.getGolesLocal()));
          JLgolesVis.setText(String.valueOf(partido.getGolesVist()));
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        JLescudoLocal2 = new javax.swing.JLabel();
        JTVist = new javax.swing.JLabel();
        JLescudoVist2 = new javax.swing.JLabel();
        JTLocal = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        JLfecha2 = new javax.swing.JLabel();
        JLlugar = new javax.swing.JLabel();
        JLarbitro = new javax.swing.JLabel();
        JLgolesLocal = new javax.swing.JLabel();
        JLgolesVis = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        JLescudoLocal2.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoLocal2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoLocal2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JTVist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTVist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTVist.setText("VISITANTE");

        JLescudoVist2.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoVist2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoVist2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JTLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTLocal.setText("LOCAL");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Informacion");

        JLfecha2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLfecha2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfecha2.setText("Fecha");

        JLlugar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLlugar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLlugar.setText("Lugar");

        JLarbitro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLarbitro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLarbitro.setText("Arbitro");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JLlugar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(JLfecha2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
            .addComponent(JLarbitro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addComponent(JLfecha2)
                .addGap(18, 18, 18)
                .addComponent(JLlugar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(JLarbitro)
                .addGap(21, 21, 21))
        );

        JLgolesLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLgolesLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLgolesLocal.setText("3");

        JLgolesVis.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JLgolesVis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLgolesVis.setText("3");

        jButton1.setText("ACEPTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("FINALIZADO");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(JLgolesLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JLgolesVis, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(107, 107, 107))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JLescudoLocal2, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                    .addComponent(JTLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(JTVist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(JLescudoVist2, javax.swing.GroupLayout.DEFAULT_SIZE, 164, Short.MAX_VALUE))
                .addGap(51, 51, 51))
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(285, 285, 285))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(50, 50, 50)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(JLgolesVis)
                    .addComponent(JLgolesLocal))
                .addGap(35, 35, 35)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTLocal)
                    .addComponent(JTVist))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLescudoLocal2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JLescudoVist2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLarbitro;
    private javax.swing.JLabel JLescudoLocal2;
    private javax.swing.JLabel JLescudoVist2;
    private javax.swing.JLabel JLfecha2;
    private javax.swing.JLabel JLgolesLocal;
    private javax.swing.JLabel JLgolesVis;
    private javax.swing.JLabel JLlugar;
    private javax.swing.JLabel JTLocal;
    private javax.swing.JLabel JTVist;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
