/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Vista;

import Logica.ActaArbitral;
import static Logica.Main.miUefa;
import Logica.Suceso;
import Persistencia.Datos;
import java.awt.BorderLayout;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author pedro ortiz
 */
public class PanelCuartos extends javax.swing.JPanel {

    /**
     * Creates new form PanelCuartos
     */
    int i;
   
    public PanelCuartos() {
        initComponents();
        i=0;
            
            JBatras.setEnabled(false);
              if(verificarCuartos()==true){
                   JOptionPane.showMessageDialog(null, "BIENVENIDO A LA SEMI FINAL DE LA UCL");
         PanelSemis panel3 = new PanelSemis();
         panel3.setSize(840, 630);
         panel3.setLocation(5, 5);
         this.removeAll();
         this.removeAll();
         this.add(panel3,BorderLayout.CENTER);
         this.revalidate();
         this.repaint();}
            mostrar();
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private boolean verificarCuartos(){
        int a=0;
        for(int i=0;i<4;i++){
    if(miUefa.getFaseFinal().getCuartosFinal().get(i).isEstado()){a++;}
        }
        
        if(a==4){ miUefa.partidosSemis(1);miUefa.partidosSemis(2);
                 miUefa.getFaseFinal().setEstadoSemi(true);
                 this.removeAll();
                 return true;
        
        }
        else{return false;}
    }
    private void mostrar(){
        System.out.println("VALOR DE i: "+i);
     JTnombreLocal.setText( miUefa.getFaseFinal().getCuartosFinal().get(i).getLocal().getNombre());
        JTnombreVist.setText( miUefa.getFaseFinal().getCuartosFinal().get(i).getVisitante().getNombre());
        JLfecha.setText( miUefa.getFaseFinal().getCuartosFinal().get(i).getFecha().getTime().toString());

        if( miUefa.getFaseFinal().getCuartosFinal().get(i).getLocal().getEscudo()!=null){

            ImageIcon icon = new ImageIcon( miUefa.getFaseFinal().getCuartosFinal().get(i).getLocal().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);

        }

        if( miUefa.getFaseFinal().getCuartosFinal().get(i).getVisitante().getEscudo()!=null){

            ImageIcon icon = new ImageIcon( miUefa.getFaseFinal().getCuartosFinal().get(i).getVisitante().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);

        }
        if(  miUefa.getFaseFinal().getCuartosFinal().get(i).isEstado()){

            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);

        }else{ JBsimulacionDet.setEnabled(true);
            JBsimulacionRap.setEnabled(true);
            JBllenarActa.setEnabled(true);}}
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        PanelSemiFinal = new org.edisoncor.gui.panel.PanelCurves();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        JTnombreLocal1 = new javax.swing.JLabel();
        JLescudoLocal1 = new javax.swing.JLabel();
        JTnombreVist1 = new javax.swing.JLabel();
        JLescudoVist1 = new javax.swing.JLabel();
        JLfecha1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        JBsimulacionRap1 = new javax.swing.JButton();
        JBllenarActa1 = new javax.swing.JButton();
        JBsimulacionDet1 = new javax.swing.JButton();
        JBsiguiente1 = new javax.swing.JButton();
        JBatras1 = new javax.swing.JButton();
        PanelInicio = new org.edisoncor.gui.panel.PanelCurves();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        JTnombreLocal = new javax.swing.JLabel();
        JLescudoLocal = new javax.swing.JLabel();
        JTnombreVist = new javax.swing.JLabel();
        JLescudoVist = new javax.swing.JLabel();
        JLfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBsimulacionRap = new javax.swing.JButton();
        JBllenarActa = new javax.swing.JButton();
        JBsimulacionDet = new javax.swing.JButton();
        JBsiguiente = new javax.swing.JButton();
        JBatras = new javax.swing.JButton();

        PanelSemiFinal.setEnabled(false);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("    SEMI FINAL");

        jButton2.setText("AVANZAR A FINAL");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JTnombreLocal1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreLocal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreLocal1.setText("LOCAL");

        JLescudoLocal1.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoLocal1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoLocal1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JTnombreVist1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreVist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreVist1.setText("VISITANTE");

        JLescudoVist1.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoVist1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoVist1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JLfecha1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLfecha1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfecha1.setText("Fecha");

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Lugar");

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Arbitro");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Informacion");

        JBsimulacionRap1.setText("SIMULACION RAPIDA");
        JBsimulacionRap1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionRap1ActionPerformed(evt);
            }
        });

        JBllenarActa1.setText("LLENAR ACTA");
        JBllenarActa1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBllenarActa1ActionPerformed(evt);
            }
        });

        JBsimulacionDet1.setText("SIMULACION DETALLADA");
        JBsimulacionDet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionDet1ActionPerformed(evt);
            }
        });

        JBsiguiente1.setText("SIGUIENTE");
        JBsiguiente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsiguiente1ActionPerformed(evt);
            }
        });

        JBatras1.setText("ATRAS");
        JBatras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatras1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBsimulacionRap1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLescudoLocal1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(JTnombreLocal1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(JBsimulacionDet1)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLfecha1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBllenarActa1)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTnombreVist1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLescudoVist1, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(JBatras1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBsiguiente1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBatras1)
                    .addComponent(JBsiguiente1))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(JTnombreVist1))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTnombreLocal1)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(JLfecha1)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel6)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addComponent(JLescudoVist1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(JLescudoLocal1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBsimulacionRap1)
                    .addComponent(JBllenarActa1)
                    .addComponent(JBsimulacionDet1))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout PanelSemiFinalLayout = new javax.swing.GroupLayout(PanelSemiFinal);
        PanelSemiFinal.setLayout(PanelSemiFinalLayout);
        PanelSemiFinalLayout.setHorizontalGroup(
            PanelSemiFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelSemiFinalLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 63, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSemiFinalLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelSemiFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSemiFinalLayout.createSequentialGroup()
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(312, 312, 312))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSemiFinalLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(265, 265, 265))))
        );
        PanelSemiFinalLayout.setVerticalGroup(
            PanelSemiFinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelSemiFinalLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel2)
                .addGap(33, 33, 33)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addComponent(jButton2)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSemiFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelSemiFinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        PanelInicio.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("CUARTOS DE FINAL");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JTnombreLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreLocal.setText("LOCAL");

        JLescudoLocal.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JTnombreVist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreVist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreVist.setText("VISITANTE");

        JLescudoVist.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoVist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoVist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JLfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfecha.setText("Fecha");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lugar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Arbitro");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Informacion");

        JBsimulacionRap.setText("SIMULACION RAPIDA");
        JBsimulacionRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionRapActionPerformed(evt);
            }
        });

        JBllenarActa.setText("LLENAR ACTA");
        JBllenarActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBllenarActaActionPerformed(evt);
            }
        });

        JBsimulacionDet.setText("SIMULACION DETALLADA");
        JBsimulacionDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionDetActionPerformed(evt);
            }
        });

        JBsiguiente.setText("SIGUIENTE");
        JBsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsiguienteActionPerformed(evt);
            }
        });

        JBatras.setText("ATRAS");
        JBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBsimulacionRap, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLescudoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(JTnombreLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JBsimulacionDet)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBllenarActa)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTnombreVist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLescudoVist, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JBatras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBatras)
                    .addComponent(JBsiguiente))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(JTnombreVist))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTnombreLocal)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(JLfecha)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(JLescudoVist, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(JLescudoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBsimulacionRap)
                    .addComponent(JBllenarActa)
                    .addComponent(JBsimulacionDet))
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(113, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(306, 306, 306))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelInicio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatrasActionPerformed

        JBsiguiente.setEnabled(true);
        i--;
        if(i==0){JBatras.setEnabled(false);}
        mostrar();

    }//GEN-LAST:event_JBatrasActionPerformed
  
    private void JBsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsiguienteActionPerformed
        // TODO add your handling code here:

        JBatras.setEnabled(true);

        i++;
        if(i==3){JBsiguiente.setEnabled(false);}
       
        mostrar();

    }//GEN-LAST:event_JBsiguienteActionPerformed

    private void JBllenarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBllenarActaActionPerformed

                if(miUefa.getFaseFinal().getCuartosFinal().get(i).isEstado()){
            
                       JOptionPane.showMessageDialog(null,"LO SENTIMOS, YA HA LLENADO ESTA ACTA");
                    }else{
                        LlenarActa acta = new LlenarActa(null, true, miUefa.getFaseFinal().getCuartosFinal().get(i));
                        acta.setLocationRelativeTo(null);
                        acta.setVisible(true);
                    }
                
    }//GEN-LAST:event_JBllenarActaActionPerformed

    private void JBsimulacionRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionRapActionPerformed
        Random num = new Random();
        ActaArbitral acta = new ActaArbitral();

        if(miUefa.getFaseFinal().getCuartosFinal().get(i).isEstado()==true){
            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);}
        else{

            Suceso suceso = new Suceso();
            Suceso suceso2 = new Suceso();

            int golesLocal = num.nextInt(num.nextInt(7)+1);
            int golesVist = num.nextInt(num.nextInt(7)+1);
            for(int k=0;k<golesLocal;k++){
                suceso = new Suceso();
                //suceso.setImplicado(miUefa.getFaseFinal().getCuartosFinal().get(i).getLocal().getJugadores().get(num.nextInt(9)+1));

                suceso.setImplicado(miUefa.getFaseFinal().getCuartosFinal().get(i).getLocal().getJugadores().get(0));
                suceso.setMinuto(num.nextInt(88)+1);
                suceso.setTipo(1);
                suceso.getImplicado().setNumGoles(suceso.getImplicado().getNumGoles()+1);
                acta.getSucesos().add(suceso);
            }

            for(int k=0;k<golesVist;k++){
                suceso2 = new Suceso();
                //suceso2.setImplicado(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getJugadores().get(num.nextInt(9)+1));
                suceso2.setImplicado(miUefa.getFaseFinal().getCuartosFinal().get(i).getVisitante().getJugadores().get(0));
                suceso2.setMinuto(num.nextInt(88)+1);
                suceso2.setTipo(1);
                suceso2.getImplicado().setNumGoles(suceso2.getImplicado().getNumGoles()+1);
                acta.getSucesos().add(suceso2);
            }

            acta.setInformacion(miUefa.getFaseFinal().getCuartosFinal().get(i));

            miUefa.getFaseFinal().getCuartosFinal().get(i).setGolesLocal(golesLocal);
            miUefa.getFaseFinal().getCuartosFinal().get(i).setGolesVist(golesVist);
            miUefa.getFaseFinal().getCuartosFinal().get(i).setActa(acta);
            miUefa.getFaseFinal().getCuartosFinal().get(i).setEstado(true);
             
            miUefa.partidoFinalizado(miUefa.getFaseFinal().getCuartosFinal().get(i));
            
            JOptionPane.showMessageDialog(null, " SIMULACION EXITOSA");
              //persistencia.guardar(miUefa);
            MostrarResultado vn = new MostrarResultado(null, true, miUefa.getFaseFinal().getCuartosFinal().get(i));
            vn.setLocationRelativeTo(null);
            vn.setVisible(true);
               
            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);
            if(verificarCuartos()==true){
                 JOptionPane.showMessageDialog(null, "BIENVENIDO A LA SEMI FINAL DE LA UCL");
         PanelSemis panel3 = new PanelSemis();
         panel3.setSize(840, 630);
         panel3.setLocation(5, 5);
         this.removeAll();
         this.removeAll();
         this.add(panel3,BorderLayout.CENTER);
         this.revalidate();
         this.repaint();}
         
        //7169
        }
    }//GEN-LAST:event_JBsimulacionRapActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void JBsimulacionRap1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionRap1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBsimulacionRap1ActionPerformed

    private void JBllenarActa1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBllenarActa1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBllenarActa1ActionPerformed

    private void JBsimulacionDet1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionDet1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBsimulacionDet1ActionPerformed

    private void JBsiguiente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsiguiente1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBsiguiente1ActionPerformed

    private void JBatras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatras1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_JBatras1ActionPerformed

    private void JBsimulacionDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionDetActionPerformed
        SimulacionPartido ven = new SimulacionPartido( miUefa.getFaseFinal().getCuartosFinal().get(i));
        ven.setLocationRelativeTo(null);
        ven.setVisible(true);
    }//GEN-LAST:event_JBsimulacionDetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBatras;
    private javax.swing.JButton JBatras1;
    private javax.swing.JButton JBllenarActa;
    private javax.swing.JButton JBllenarActa1;
    private javax.swing.JButton JBsiguiente;
    private javax.swing.JButton JBsiguiente1;
    private javax.swing.JButton JBsimulacionDet;
    private javax.swing.JButton JBsimulacionDet1;
    private javax.swing.JButton JBsimulacionRap;
    private javax.swing.JButton JBsimulacionRap1;
    private javax.swing.JLabel JLescudoLocal;
    private javax.swing.JLabel JLescudoLocal1;
    private javax.swing.JLabel JLescudoVist;
    private javax.swing.JLabel JLescudoVist1;
    private javax.swing.JLabel JLfecha;
    private javax.swing.JLabel JLfecha1;
    private javax.swing.JLabel JTnombreLocal;
    private javax.swing.JLabel JTnombreLocal1;
    private javax.swing.JLabel JTnombreVist;
    private javax.swing.JLabel JTnombreVist1;
    private org.edisoncor.gui.panel.PanelCurves PanelInicio;
    private org.edisoncor.gui.panel.PanelCurves PanelSemiFinal;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
