/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pedro ortiz
 */
import Logica.ActaArbitral;
import static Logica.Main.miUefa;
import Logica.Suceso;
import Persistencia.Datos;
import java.awt.BorderLayout;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
public class PanelSemis extends javax.swing.JPanel {

    /**
     * Creates new form PanelSemis
     */
    int i;
    int j;
    public PanelSemis() {
        initComponents();
        i=0;j=0;
        JBatras.setEnabled(false);
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JTnombreLocal = new javax.swing.JLabel();
        JLescudoLocal = new javax.swing.JLabel();
        JTnombreVist = new javax.swing.JLabel();
        JLescudoVist = new javax.swing.JLabel();
        JLfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        JBsimulacionRap = new javax.swing.JButton();
        JBllenarActa = new javax.swing.JButton();
        JBsimulacionDet = new javax.swing.JButton();
        JBsiguiente = new javax.swing.JButton();
        JBatras = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JTnombreLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreLocal.setText("LOCAL");

        JLescudoLocal.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JTnombreVist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreVist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreVist.setText("VISITANTE");

        JLescudoVist.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoVist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoVist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JLfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfecha.setText("Fecha");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lugar");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Arbitro");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Informacion");

        JBsimulacionRap.setText("SIMULACION RAPIDA");
        JBsimulacionRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionRapActionPerformed(evt);
            }
        });

        JBllenarActa.setText("LLENAR ACTA");
        JBllenarActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBllenarActaActionPerformed(evt);
            }
        });

        JBsimulacionDet.setText("SIMULACION DETALLADA");
        JBsimulacionDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionDetActionPerformed(evt);
            }
        });

        JBsiguiente.setText("SIGUIENTE");
        JBsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsiguienteActionPerformed(evt);
            }
        });

        JBatras.setText("ATRAS");
        JBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBsimulacionRap, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLescudoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(JTnombreLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(JBsimulacionDet)
                        .addGap(34, 34, 34))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(57, 57, 57))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(JLfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(75, 75, 75))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(JBllenarActa)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(73, 73, 73)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTnombreVist, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JLescudoVist, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE))
                        .addGap(20, 20, 20))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JBatras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBatras)
                    .addComponent(JBsiguiente))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(JTnombreVist))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(JTnombreLocal)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(JLfecha)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4))
                            .addComponent(JLescudoVist, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(JLescudoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBsimulacionRap)
                    .addComponent(JBllenarActa)
                    .addComponent(JBsimulacionDet))
                .addGap(30, 30, 30))
        );

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("SEMI FINAL");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(361, 361, 361))
            .addGroup(layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(193, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents
 private void mostrar(){
        System.out.println("VALOR DE i: "+i);
     JTnombreLocal.setText( miUefa.getFaseFinal().getSemiFinal().get(i).getLocal().getNombre());
        JTnombreVist.setText( miUefa.getFaseFinal().getSemiFinal().get(i).getVisitante().getNombre());
        JLfecha.setText( miUefa.getFaseFinal().getSemiFinal().get(i).getFecha().getTime().toString());

        if( miUefa.getFaseFinal().getSemiFinal().get(i).getLocal().getEscudo()!=null){

            ImageIcon icon = new ImageIcon( miUefa.getFaseFinal().getSemiFinal().get(i).getLocal().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);

        }

        if( miUefa.getFaseFinal().getSemiFinal().get(i).getVisitante().getEscudo()!=null){

            ImageIcon icon = new ImageIcon( miUefa.getFaseFinal().getSemiFinal().get(i).getVisitante().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);

        }
        if(  miUefa.getFaseFinal().getSemiFinal().get(i).isEstado()){

            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);

        }else{ JBsimulacionDet.setEnabled(true);
            JBsimulacionRap.setEnabled(true);
            JBllenarActa.setEnabled(true);}}
 
    private void JBsimulacionRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionRapActionPerformed
        Random num = new Random();
        ActaArbitral acta = new ActaArbitral();

        if(miUefa.getFaseFinal().getSemiFinal().get(i).isEstado()==true){
            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);}
        else{

            Suceso suceso = new Suceso();
            Suceso suceso2 = new Suceso();

            int golesLocal = num.nextInt(num.nextInt(7)+1);
            int golesVist = num.nextInt(num.nextInt(7)+1);
            for(int k=0;k<golesLocal;k++){
                suceso = new Suceso();
                //suceso.setImplicado(miUefa.getFaseFinal().getCuartosFinal().get(i).getLocal().getJugadores().get(num.nextInt(9)+1));

                suceso.setImplicado(miUefa.getFaseFinal().getSemiFinal().get(i).getLocal().getJugadores().get(0));
                suceso.setMinuto(num.nextInt(88)+1);
                suceso.setTipo(1);
                suceso.getImplicado().setNumGoles(suceso.getImplicado().getNumGoles()+1);
                acta.getSucesos().add(suceso);
            }

            for(int k=0;k<golesVist;k++){
                suceso2 = new Suceso();
                //suceso2.setImplicado(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getJugadores().get(num.nextInt(9)+1));
                suceso2.setImplicado(miUefa.getFaseFinal().getSemiFinal().get(i).getVisitante().getJugadores().get(0));
                suceso2.setMinuto(num.nextInt(88)+1);
                suceso2.setTipo(1);
                suceso2.getImplicado().setNumGoles(suceso2.getImplicado().getNumGoles()+1);
                acta.getSucesos().add(suceso2);
            }

            acta.setInformacion(miUefa.getFaseFinal().getSemiFinal().get(i));

            miUefa.getFaseFinal().getSemiFinal().get(i).setGolesLocal(golesLocal);
            miUefa.getFaseFinal().getSemiFinal().get(i).setGolesVist(golesVist);
            miUefa.getFaseFinal().getSemiFinal().get(i).setActa(acta);
            miUefa.getFaseFinal().getSemiFinal().get(i).setEstado(true);

            miUefa.partidoFinalizado(miUefa.getFaseFinal().getSemiFinal().get(i));
            System.out.println("ESTADO DESPUES: "+miUefa.getFaseFinal().getSemiFinal().get(i).isEstado());
            JOptionPane.showMessageDialog(null, " SIMULACION EXITOSA");
            //persistencia.guardar(miUefa);
            MostrarResultado vn = new MostrarResultado(null, true, miUefa.getFaseFinal().getSemiFinal().get(i));
            vn.setLocationRelativeTo(null);
            vn.setVisible(true);

            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);
  if(verificarSemis()==true){
                 JOptionPane.showMessageDialog(null, "BIENVENIDO A LA FINAL DE LA UCL");
         PanelPartidoFinal panel3 = new PanelPartidoFinal();
         panel3.setSize(840, 630);
         panel3.setLocation(5, 5);
         this.removeAll();
         this.removeAll();
         this.add(panel3,BorderLayout.CENTER);
         this.revalidate();
         this.repaint();}
            //7169
        }
    }//GEN-LAST:event_JBsimulacionRapActionPerformed
  private boolean verificarSemis(){
  
  if(miUefa.getFaseFinal().getSemiFinal().get(0).isEstado()
          && miUefa.getFaseFinal().getSemiFinal().get(1).isEstado()){
  miUefa.partidoFinal();
  miUefa.getFaseFinal().setEstadoFinal(true);
  return true;
  
  }else{return false;}
  
  
  
  
  
  }
    private void JBllenarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBllenarActaActionPerformed

                if(miUefa.getFaseFinal().getCuartosFinal().get(i).isEstado()){
            
                        JOptionPane.showMessageDialog(null,"LO SENTIMOS, YA HA LLENADO ESTA ACTA");
                    }else{
                        LlenarActa acta = new LlenarActa(null, true, miUefa.getFaseFinal().getCuartosFinal().get(i));
                        acta.setLocationRelativeTo(null);
                        acta.setVisible(true);
                    }
    }//GEN-LAST:event_JBllenarActaActionPerformed

    private void JBsimulacionDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionDetActionPerformed
        SimulacionPartido ven = new SimulacionPartido( miUefa.getFaseFinal().getSemiFinal().get(i));
        ven.setLocationRelativeTo(null);
        ven.setVisible(true);
    }//GEN-LAST:event_JBsimulacionDetActionPerformed

    private void JBsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsiguienteActionPerformed
        // TODO add your handling code here:

        JBatras.setEnabled(true);

        i++;
        if(i==1){JBsiguiente.setEnabled(false);}

        mostrar();
    }//GEN-LAST:event_JBsiguienteActionPerformed

    private void JBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatrasActionPerformed

        JBsiguiente.setEnabled(true);
        i--;
        if(i==0){JBatras.setEnabled(false);}
        mostrar();
    }//GEN-LAST:event_JBatrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JBatras;
    private javax.swing.JButton JBllenarActa;
    private javax.swing.JButton JBsiguiente;
    private javax.swing.JButton JBsimulacionDet;
    private javax.swing.JButton JBsimulacionRap;
    private javax.swing.JLabel JLescudoLocal;
    private javax.swing.JLabel JLescudoVist;
    private javax.swing.JLabel JLfecha;
    private javax.swing.JLabel JTnombreLocal;
    private javax.swing.JLabel JTnombreVist;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
