/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author pedro ortiz
 */

import Logica.ActaArbitral;

import static Logica.Main.miUefa;
import Logica.Suceso;
import Persistencia.Datos;
import java.awt.BorderLayout;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

public class PanelFaseGrupos extends javax.swing.JPanel {

    /**
     * Creates new form PanelFaseGrupos
     */int i;
     int j;
     Datos persistencia;
    public PanelFaseGrupos() {
        initComponents();
        persistencia = new Datos();
        i=0;j=0;
         if(verificarFaseGrupos()==true){
              JOptionPane.showMessageDialog(null, "BIENVENIDO A CUARTOS DE FINAL DE LA UCL");
         PanelCuartos panel3 = new PanelCuartos();
         panel3.setSize(840, 630);
         panel3.setLocation(5, 5);
         this.removeAll();
         this.removeAll();
         this.add(panel3,BorderLayout.CENTER);
         this.revalidate();
         this.repaint();}
            mostrar();
            JB0.setEnabled(false);
            JBatras.setEnabled(false);
            
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelInicio = new org.edisoncor.gui.panel.PanelCurves();
        jPanel1 = new javax.swing.JPanel();
        JTnombreLocal = new javax.swing.JLabel();
        JLescudoLocal = new javax.swing.JLabel();
        JTnombreVist = new javax.swing.JLabel();
        JLescudoVist = new javax.swing.JLabel();
        JBsimulacionRap = new javax.swing.JButton();
        JBllenarActa = new javax.swing.JButton();
        JBsimulacionDet = new javax.swing.JButton();
        JBsiguiente = new javax.swing.JButton();
        JBatras = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        JLfecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        JLgrupo = new javax.swing.JLabel();
        JB1 = new javax.swing.JButton();
        JB0 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        PanelInicio.setEnabled(false);

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JTnombreLocal.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreLocal.setText("LOCAL");

        JLescudoLocal.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoLocal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoLocal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JTnombreVist.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        JTnombreVist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JTnombreVist.setText("VISITANTE");

        JLescudoVist.setBackground(new java.awt.Color(204, 204, 204));
        JLescudoVist.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLescudoVist.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Shield-128.png"))); // NOI18N

        JBsimulacionRap.setText("SIMULACION RAPIDA");
        JBsimulacionRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionRapActionPerformed(evt);
            }
        });

        JBllenarActa.setText("LLENAR ACTA");
        JBllenarActa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBllenarActaActionPerformed(evt);
            }
        });

        JBsimulacionDet.setText("SIMULACION DETALLADA");
        JBsimulacionDet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsimulacionDetActionPerformed(evt);
            }
        });

        JBsiguiente.setText("SIGUIENTE");
        JBsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBsiguienteActionPerformed(evt);
            }
        });

        JBatras.setText("ATRAS");
        JBatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JBatrasActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Informacion");

        JLfecha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        JLfecha.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLfecha.setText("Fecha");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Lugar");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(29, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(JLfecha, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(46, 46, 46))
        );

        JLgrupo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        JLgrupo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLgrupo.setText("GRUPO");

        JB1.setText(">");
        JB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB1ActionPerformed(evt);
            }
        });

        JB0.setText("<");
        JB0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JB0ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JBsimulacionRap, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JLescudoLocal, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                            .addComponent(JTnombreLocal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(JBllenarActa))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(70, 70, 70)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(JBsimulacionDet)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JTnombreVist, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLescudoVist, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 43, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(JBatras, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JBsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(JB0, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(JLgrupo, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JB1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(203, 203, 203))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JBatras)
                    .addComponent(JBsiguiente))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(JTnombreLocal))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JLgrupo)
                            .addComponent(JB0)
                            .addComponent(JB1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(JTnombreVist)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(JLescudoLocal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(JLescudoVist, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(JBsimulacionRap)
                            .addComponent(JBllenarActa)
                            .addComponent(JBsimulacionDet))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("FASE DE GRUPOS");

        javax.swing.GroupLayout PanelInicioLayout = new javax.swing.GroupLayout(PanelInicio);
        PanelInicio.setLayout(PanelInicioLayout);
        PanelInicioLayout.setHorizontalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelInicioLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 385, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );
        PanelInicioLayout.setVerticalGroup(
            PanelInicioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelInicioLayout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jLabel6)
                .addGap(52, 52, 52)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 10, Short.MAX_VALUE)
                .addComponent(PanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelInicio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 28, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JBsimulacionRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionRapActionPerformed
        Random num = new Random();
        ActaArbitral acta = new ActaArbitral();

        if(miUefa.getGrupos().get(i).getPartidos().get(j).isEstado()){
            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);}
        else{

            Suceso suceso = new Suceso();
            Suceso suceso2 = new Suceso();

            int golesLocal = num.nextInt(num.nextInt(5)+1);
            int golesVist = num.nextInt(num.nextInt(5)+1);
            for(int k=0;k<golesLocal;k++){
                suceso = new Suceso();
                //suceso.setImplicado(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getJugadores().get(num.nextInt(9)+1));

                suceso.setImplicado(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getJugadores().get(0));
                suceso.setMinuto(num.nextInt(88)+1);
                suceso.setTipo(1);
                suceso.getImplicado().setNumGoles(suceso.getImplicado().getNumGoles()+1);
                acta.getSucesos().add(suceso);
            }

            for(int k=0;k<golesVist;k++){
                suceso2 = new Suceso();
                //suceso2.setImplicado(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getJugadores().get(num.nextInt(9)+1));
                suceso2.setImplicado(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getJugadores().get(0));
                suceso2.setMinuto(num.nextInt(88)+1);
                suceso2.setTipo(1);
                suceso2.getImplicado().setNumGoles(suceso2.getImplicado().getNumGoles()+1);
                acta.getSucesos().add(suceso2);
            }

            acta.setInformacion(miUefa.getGrupos().get(i).getPartidos().get(j));

            miUefa.getGrupos().get(i).getPartidos().get(j).setGolesLocal(golesLocal);
            miUefa.getGrupos().get(i).getPartidos().get(j).setGolesVist(golesVist);
            miUefa.getGrupos().get(i).getPartidos().get(j).setActa(acta);
            miUefa.getGrupos().get(i).getPartidos().get(j).setEstado(true);

            miUefa.partidoFinalizado(miUefa.getGrupos().get(i).getPartidos().get(j));
            JOptionPane.showMessageDialog(null, " SIMULACION EXITOSA");

            MostrarResultado vn = new MostrarResultado(null, true, miUefa.getGrupos().get(i)
                .getPartidos().get(j));
            vn.setLocationRelativeTo(null);
            vn.setVisible(true);

            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);
    
            persistencia.guardar(miUefa);
             if(verificarFaseGrupos()==true){
                 JOptionPane.showMessageDialog(null, "BIENVENIDO A CUARTOS DE FINAL DE LA UCL");
         PanelCuartos panel3 = new PanelCuartos();
         panel3.setSize(840, 630);
         panel3.setLocation(5, 5);
         this.removeAll();
         this.removeAll();
         this.add(panel3,BorderLayout.CENTER);
         this.revalidate();
         this.repaint();}
            // FALTA CAMBIARLE EL ESTADO CUANDO SE LLENE EL ACTA O SIMULE CON DETALLADAMENTE
      JBatras.setEnabled(false);
      JB0.setEnabled(true);
        }
      
    }//GEN-LAST:event_JBsimulacionRapActionPerformed
  private boolean verificarFaseGrupos(){
  int cont=0;
  for(int i=0;i<4;i++){
      
  for(int k=0;k<miUefa.getGrupos().get(i).getPartidos().size();k++){
      
  
     if(miUefa.getGrupos().get(i).getPartidos().get(k).isEstado()){cont++;}
  }
  
  }
  if(cont==48){
      for(int i=0;i<4;i++){
          miUefa.establecerClasificacion(i);
          miUefa.partidosCuartos(i);}
      
      
      miUefa.setEstadoGrupos(true);return true;}
  else{return false;}
  
  }
    private void JBllenarActaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBllenarActaActionPerformed

        if(miUefa.getGrupos().get(i).getPartidos().get(j).isEstado()){

            JOptionPane.showMessageDialog(null,"LO SENTIMOS, YA HA LLENADO ESTA ACTA");
        }else{
            LlenarActa acta = new LlenarActa(null, true, miUefa.getGrupos().get(i).getPartidos().get(j));
            acta.setLocationRelativeTo(null);
            acta.setVisible(true);
        }

    }//GEN-LAST:event_JBllenarActaActionPerformed

    private void JBsimulacionDetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsimulacionDetActionPerformed
        SimulacionPartido ven = new SimulacionPartido(miUefa.getGrupos().get(i).getPartidos().get(j));
        ven.setLocationRelativeTo(null);
        ven.setVisible(true);
    }//GEN-LAST:event_JBsimulacionDetActionPerformed

    private void JBsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBsiguienteActionPerformed
        // TODO add your handling code here:
          j++;
        JBatras.setEnabled(true);
       
        if(j==11){JBsiguiente.setEnabled(false);}
        mostrar();
    }//GEN-LAST:event_JBsiguienteActionPerformed

    private void JBatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JBatrasActionPerformed

        j--;
         JBsiguiente.setEnabled(true);
        if(j==0){JBatras.setEnabled(false);}
      

            mostrar();
    }//GEN-LAST:event_JBatrasActionPerformed

    private void JB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB1ActionPerformed
      i++;
      j=0;
      JB0.setEnabled(true);
      if(i==3){JB1.setEnabled(false);}
      mostrar();
    }//GEN-LAST:event_JB1ActionPerformed

    private void JB0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JB0ActionPerformed
        i--;
        JB1.setEnabled(true);
      if(i==0){JB0.setEnabled(false);}
      mostrar();
      
    }//GEN-LAST:event_JB0ActionPerformed
private void mostrar(){
    String aux="";    
    if(i==0){aux="GRUPO A";}  if(i==2){aux="GRUPO C";}
      if(i==1){aux="GRUPO B";}  if(i==3){aux="GRUPO D";}
      
      JLgrupo.setText(aux);
      
        JTnombreLocal.setText(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getNombre());
        JTnombreVist.setText(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getNombre());
        JLfecha.setText(miUefa.getGrupos().get(i).getPartidos().get(j).getFecha().toString());
        if(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getEscudo()!=null){

            ImageIcon icon = new ImageIcon(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);

        }

        if(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getEscudo()!=null){

            ImageIcon icon = new ImageIcon(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);

        }
        if( miUefa.getGrupos().get(i).getPartidos().get(j).isEstado()){

            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);

        }else{ JBsimulacionDet.setEnabled(true);
            JBsimulacionRap.setEnabled(true);
            JBllenarActa.setEnabled(true);}

        JTnombreLocal.setText(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getNombre());
        JTnombreVist.setText(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getNombre());
        JLfecha.setText(miUefa.getGrupos().get(i).getPartidos().get(j).getFecha().getTime().toString());

        if(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getEscudo()!=null){

            ImageIcon icon = new ImageIcon(miUefa.getGrupos().get(i).getPartidos().get(j).getLocal().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoLocal.setText(null);
            JLescudoLocal.setIcon(icono);

        }

        if(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getEscudo()!=null){

            ImageIcon icon = new ImageIcon(miUefa.getGrupos().get(i).getPartidos().get(j).getVisitante().getEscudo());
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);
        }
        else{

            ImageIcon icon = new ImageIcon("src/Imagenes/Shield-128.png");
            Icon icono = new ImageIcon(icon.getImage());
            JLescudoVist.setText(null);
            JLescudoVist.setIcon(icono);

        }
        if( miUefa.getGrupos().get(i).getPartidos().get(j).isEstado()){

            JBsimulacionDet.setEnabled(false);
            JBsimulacionRap.setEnabled(false);
            JBllenarActa.setEnabled(false);

        }else{ JBsimulacionDet.setEnabled(true);
            JBsimulacionRap.setEnabled(true);
            JBllenarActa.setEnabled(true);}
       //}
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JB0;
    private javax.swing.JButton JB1;
    private javax.swing.JButton JBatras;
    private javax.swing.JButton JBllenarActa;
    private javax.swing.JButton JBsiguiente;
    private javax.swing.JButton JBsimulacionDet;
    private javax.swing.JButton JBsimulacionRap;
    private javax.swing.JLabel JLescudoLocal;
    private javax.swing.JLabel JLescudoVist;
    private javax.swing.JLabel JLfecha;
    private javax.swing.JLabel JLgrupo;
    private javax.swing.JLabel JTnombreLocal;
    private javax.swing.JLabel JTnombreVist;
    private org.edisoncor.gui.panel.PanelCurves PanelInicio;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
