/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Logica.Equipo;
import Logica.Jugador;
import static Logica.Main.miUefa;
import Persistencia.Datos;
import java.io.Serializable;

import javax.swing.JOptionPane;

/**
 *
 * @author pedro ortiz
 */
public class Sorteo extends javax.swing.JFrame implements Serializable{

    /**
     * Creates new form Sorteo2
     */
   
   Datos persistencia; 
    public Sorteo() {
        initComponents();
            persistencia = new Datos();
           
        String[] vector = new String[miUefa.getParticipantes().size()];
        for (int i = 0; i < miUefa.getParticipantes().size(); i++) {
          vector[i]=miUefa.getParticipantes().get(i).getNombre();
            System.out.println(vector[i]);
        }
        JLinscritos.setListData(vector);
    }
    
    
    
    public void actualizar(){
    
        String[] vector = new String[miUefa.getParticipantes().size()];
        for (int i = 0; i < miUefa.getParticipantes().size(); i++) {
          vector[i]=miUefa.getParticipantes().get(i).getNombre();
            System.out.println(vector[i]);
        }
        JLinscritos.setListData(vector);
    
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        JLinscritos = new javax.swing.JList();
        jButton1 = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setModalExclusionType(java.awt.Dialog.ModalExclusionType.APPLICATION_EXCLUDE);
        setResizable(false);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "EQUIPOS INSCRITOS", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP));

        JLinscritos.setBackground(new java.awt.Color(240, 240, 240));
        JLinscritos.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        JLinscritos.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(JLinscritos);

        jButton1.setText("INICIAR SORTEO");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuBar1.setMaximumSize(new java.awt.Dimension(400, 32769));
        jMenuBar1.setPreferredSize(new java.awt.Dimension(380, 37));

        jMenu2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu2.setText("REGISTRAR EQUIPO");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("NUEVO");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem2.setText("EXISTENTE");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem4.setText("CARGAR ");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jMenu4.setText("ACCESIBILIDAD");

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setText("SALIR");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem3);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
       if(miUefa.getParticipantes().size()==16){JOptionPane.showMessageDialog(null, " YA HAY 16 EQUIPOS INSCRITOS ");}
      else{
        EquipoNuevo a = new EquipoNuevo(null, true);
        a.setLocationRelativeTo(null);    
        a.setVisible(true);
        this.setVisible(false);
        if(a.isVisible()==false){
         this.actualizar();
       this.setVisible(true);
       this.setLocationRelativeTo(null);
        }
        
      }
        
      
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     if(miUefa.getParticipantes().size()!=16){
         JOptionPane.showMessageDialog(null, " NO HAY 16 EQUIPOS REGISTRADOS ");}     
     else{
         
         
             // GRUPO 1   //GRUPO 2    //GRUPO 3   //GRUPO 4
             // A-B C-D    //A-B C-D    //A-B C-D   //A-B  C-D
             // A-C B-D
             // A-D B-C
             
             
             
             this.actualizar();
             miUefa.empezarSorteo();
             
             
             miUefa.generarFechasPartidos(0);//grupo1
             miUefa.generarFechasPartidos(1);//grupo2
             miUefa.generarFechasPartidos(2);//grupo3
             miUefa.generarFechasPartidos(3);//grupo4
             miUefa.setEstado(true);
             persistencia.guardar(miUefa);
             dispose();
             Grupos ve = new Grupos ();
             ve.setVisible(true);
             ve.setLocationRelativeTo(null);
         
     }
   

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed

   System.exit(0);
// TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
 if(miUefa.getParticipantes().size()==16){System.out.println("YA HAY 16 INSCRITOS");}
      else{
        EquipoExistente nuevo = new EquipoExistente(null, true);
        nuevo.setLocationRelativeTo(null);
        nuevo.setVisible(true);
        if(nuevo.isVisible()==false){
         this.actualizar();
        this.setVisible(true);
        this.setLocationRelativeTo(null);
        }
 }
            

    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
         for(int i=0;i<16;i++){
          
         Equipo n = new Equipo();
         n.setNombre("EQUIPO "+i);
         Jugador jug = new Jugador("SI",null, null, n, "PEDRO "+i, null, null, null, null);
         Jugador jug2 = new Jugador("NO", null,null, n, "JUAN "+i, "", " ", "COL", null);
         n.getJugadores().add(jug);
         n.getJugadores().add(jug2);
         miUefa.getParticipantes().add(n);
         
         }  
        persistencia.guardar(miUefa);     
        
    }//GEN-LAST:event_jMenuItem4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JList JLinscritos;
    private javax.swing.JButton jButton1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
